language: erlang
otp_release:
   - R16B02
#   - R16B01
#   - R15B03
script:
  - rebar get-deps
  - rebar compile 
  - rebar eunit -v skip_deps=true
  - ./script/ci/make-plt.sh
  - ./script/ci/dialyzer.sh
notifications:
  email: false