language: erlang
otp_release:
   - R16B02
   - R16B01

script:
  - rebar get-deps
  - rebar compile 
  - rebar eunit  skip_deps=true
notifications:
  email: false 

#  - mkdir plt
#  - ./travis-dialyzer.sh
