language: erlang
otp_release:
   - R16B02
   - R16B01

script:
  - rebar get-deps
  - rebar compile 
  - rebar eunit skip_deps=true
  - ./travis-dialyzer.sh
notifications:
  email: false 

#  - mkdir plt
# 
