language: erlang
otp_release:
   - R16B02
   - R16B01
   - R15B03
script:
  - rebar get-deps
  - rebar compile 
  - "./make_plt.sh"
  - rebar eunit -v skip_deps=true
  - sh ./dialyzer.sh
notifications:
  email: false