language: erlang
otp_release:
   - R16B02
#   - R16B01
#   - R15B03
script:
  - rebar get-deps
  - rebar compile 
  - rebar eunit -v skip_deps=true
  - ls -l *.sh
  - mkdir plt
  - ./make-plt.sh
  - ./dialyzer.sh
notifications:
  email: false